version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    ports:
      - "53306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: sample_db
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always

volumes:
  mysql-data:
