CREATE TABLE users( 
    id INT AUTO_INCREMENT PRIMARY KEY
    , username VARCHAR (50) NOT NULL
    , email VARCHAR (100) NOT NULL
    , created_at DATETIME DEFAULT CURRENT_TIMESTAMP
    , updated_at DATETIME DEFAULT CURRENT_TIMESTAMP 
        ON UPDATE CURRENT_TIMESTAMP
        , is_active BOOLEAN DEFAULT TRUE
);

